module Post exposing (view)

import Html exposing (..)
import Html.Attributes exposing (action, alt, attribute, class, href, id, placeholder, src, type_)
import Svg
import Svg.Attributes


view : Html msg
view =
    main_ []
        [ nav [ class "fixed w-full z-10 top-0", id "header" ]
            [ div [ class "h-1 z-20 top-0", id "progress", attribute "style" "background:linear-gradient(to right, #4dc0b5 var(--scroll), transparent 0);" ]
                []
            , div [ class "w-full md:max-w-4xl mx-auto flex flex-wrap items-center justify-between mt-0 py-3" ]
                [ div [ class "pl-4" ]
                    [ a [ class "text-gray-900 text-base no-underline hover:no-underline font-extrabold text-xl", href "#" ]
                        [ text "Minimal Blog\t\t\t\t" ]
                    ]
                , div [ class "block lg:hidden pr-4" ]
                    [ button [ class "flex items-center px-3 py-2 border rounded text-gray-500 border-gray-600 hover:text-gray-900 hover:border-green-500 appearance-none focus:outline-none", id "nav-toggle" ]
                        [ Svg.svg [ Svg.Attributes.class "fill-current h-3 w-3", Svg.Attributes.viewBox "0 0 20 20", attribute "xmlns" "http://www.w3.org/2000/svg" ]
                            [ Svg.node "title"
                                []
                                [ text "Menu" ]
                            , Svg.path [ Svg.Attributes.d "M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z" ]
                                []
                            , Svg.text "\t\t\t\t\t"
                            ]
                        ]
                    ]
                , div [ class "w-full flex-grow lg:flex lg:items-center lg:w-auto hidden lg:block mt-2 lg:mt-0 bg-gray-100 md:bg-transparent z-20", id "nav-content" ]
                    [ ul [ class "list-reset lg:flex justify-end flex-1 items-center" ]
                        [ li [ class "mr-3" ]
                            [ a [ class "inline-block py-2 px-4 text-gray-900 font-bold no-underline", href "#" ]
                                [ text "Active" ]
                            ]
                        , li [ class "mr-3" ]
                            [ a [ class "inline-block text-gray-600 no-underline hover:text-gray-900 hover:text-underline py-2 px-4", href "#" ]
                                [ text "link" ]
                            ]
                        , li [ class "mr-3" ]
                            [ a [ class "inline-block text-gray-600 no-underline hover:text-gray-900 hover:text-underline py-2 px-4", href "#" ]
                                [ text "link" ]
                            ]
                        ]
                    ]
                ]
            ]
        , div [ class "container w-full md:max-w-3xl mx-auto pt-20" ]
            [ div [ class "w-full px-4 md:px-6 text-xl text-gray-800 leading-normal", attribute "style" "font-family:Georgia,serif;" ]
                [ div [ class "font-sans" ]
                    [ p [ class "text-base md:text-sm text-green-500 font-bold" ]
                        [ text "< "
                        , a [ class "text-base md:text-sm text-green-500 font-bold no-underline hover:underline", href "#" ]
                            [ text "BACK TO BLOG" ]
                        ]
                    , h1 [ class "font-bold font-sans break-normal text-gray-900 pt-6 pb-2 text-3xl md:text-4xl" ]
                        [ text "Welcome to Minimal Blog" ]
                    , p [ class "text-sm md:text-base font-normal text-gray-600" ]
                        [ text "Published 19 February 2019" ]
                    ]
                , p [ class "py-6" ]
                    [ text "👋 Welcome fellow "
                    , a [ class "text-green-500 no-underline hover:underline", href "https://www.tailwindcss.com" ]
                        [ text "Tailwind CSS" ]
                    , text "and miminal monochrome blog fan. This starter template provides a starting point to create your own minimal monochrome blog using Tailwind CSS and vanilla Javascript.\t\t\t"
                    ]
                , p [ class "py-6" ]
                    [ text "The basic blog page layout is available and all using the default Tailwind CSS classes (although there are a few hardcoded style tags). If you are going to use this in your project, you will want to convert the classes into components." ]
                , h1 [ class "py-2 font-sans" ]
                    [ text "Heading 1" ]
                , h2 [ class "py-2 font-sans" ]
                    [ text "Heading 2" ]
                , h3 [ class "py-2 font-sans" ]
                    [ text "Heading 3" ]
                , h4 [ class "py-2 font-sans" ]
                    [ text "Heading 4" ]
                , h5 [ class "py-2 font-sans" ]
                    [ text "Heading 5" ]
                , h6 [ class "py-2 font-sans" ]
                    [ text "Heading 6" ]
                , p [ class "py-6" ]
                    [ text "Sed dignissim lectus ut tincidunt vulputate. Fusce tincidunt lacus purus, in mattis tortor sollicitudin pretium. Phasellus at diam posuere, scelerisque nisl sit amet, tincidunt urna. Cras nisi diam, pulvinar ut molestie eget, eleifend ac magna. Sed at lorem condimentum, dignissim lorem eu, blandit massa. Phasellus eleifend turpis vel erat bibendum scelerisque. Maecenas id risus dictum, rhoncus odio vitae, maximus purus. Etiam efficitur dolor in dolor molestie ornare. Aenean pulvinar diam nec neque tincidunt, vitae molestie quam fermentum. Donec ac pretium diam. Suspendisse sed odio risus. Nunc nec luctus nisi. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Duis nec nulla eget sem dictum elementum." ]
                , ol []
                    [ li [ class "py-3" ]
                        [ text "Maecenas accumsan lacus sit amet elementum porta. Aliquam eu libero lectus. Fusce vehicula dictum mi. In non dolor at sem ullamcorper venenatis ut sed dui. Ut ut est quam. Suspendisse quam quam, commodo sit amet placerat in, interdum a ipsum. Morbi sit amet tellus scelerisque tortor semper posuere." ]
                    , li [ class "py-3" ]
                        [ text "Morbi varius posuere blandit. Praesent gravida bibendum neque eget commodo. Duis auctor ornare mauris, eu accumsan odio viverra in. Proin sagittis maximus pharetra. Nullam lorem mauris, faucibus ut odio tempus, ultrices aliquet ex. Nam id quam eget ipsum luctus hendrerit. Ut eros magna, eleifend ac ornare vulputate, pretium nec felis." ]
                    , li [ class "py-3" ]
                        [ text "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nunc vitae pretium elit. Cras leo mauris, tristique in risus ac, tristique rutrum velit. Mauris accumsan tempor felis vitae gravida. Cras egestas convallis malesuada. Etiam ac ante id tortor vulputate pretium. Maecenas vel sapien suscipit, elementum odio et, consequat tellus." ]
                    ]
                , blockquote [ class "border-l-4 border-green-500 italic my-8 pl-8 md:pl-12" ]
                    [ text "Example of blockquote - Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam at ipsum eu nunc commodo posuere et sit amet ligula." ]
                , p [ class "py-6" ]
                    [ text "Example code block:" ]
                , pre [ class "bg-gray-900 rounded text-white font-mono text-base p-2 md:p-4" ]
                    [ code [ class "break-words whitespace-pre-wrap" ]
                        [ text "<header class=\"site-header outer\"><div class=\"inner\">{{> \"site-nav\"}}</div></header>\t\t\t\t" ]
                    ]
                , text "\t\t"
                ]
            , div [ class "text-base md:text-sm text-gray-500 px-4 py-6" ]
                [ text "Tags: "
                , a [ class "text-base md:text-sm text-green-500 no-underline hover:underline", href "#" ]
                    [ text "Link" ]
                , text ". "
                , a [ class "text-base md:text-sm text-green-500 no-underline hover:underline", href "#" ]
                    [ text "Link" ]
                ]
            , hr [ class "border-b-2 border-gray-400 mb-8 mx-4" ]
                []
            , div [ class "container px-4" ]
                [ div [ class "font-sans bg-gradient-to-b from-green-100 to-gray-100 rounded-lg shadow-xl p-4 text-center" ]
                    [ h2 [ class "font-bold break-normal text-xl md:text-3xl" ]
                        [ text "Subscribe to my Newsletter" ]
                    , h3 [ class "font-bold break-normal text-gray-600 text-sm md:text-base" ]
                        [ text "Get the latest posts delivered right to your inbox" ]
                    , div [ class "w-full text-center pt-4" ]
                        [ form [ action "#" ]
                            [ div [ class "max-w-xl mx-auto p-1 pr-0 flex flex-wrap items-center" ]
                                [ input [ class "flex-1 mt-4 appearance-none border border-gray-400 rounded shadow-md p-3 text-gray-600 mr-2 focus:outline-none", placeholder "youremail@example.com", type_ "email" ]
                                    []
                                , button [ class "flex-1 mt-4 block md:inline-block appearance-none bg-green-500 text-white text-base font-semibold tracking-wider uppercase py-4 rounded shadow hover:bg-green-400", type_ "submit" ]
                                    [ text "Subscribe" ]
                                ]
                            ]
                        ]
                    ]
                ]
            , text "\t\t"
            , div [ class "flex w-full items-center font-sans px-4 py-12" ]
                [ img [ alt "Avatar of Author", class "w-10 h-10 rounded-full mr-4", src "http://i.pravatar.cc/300" ]
                    []
                , div [ class "flex-1 px-2" ]
                    [ p [ class "text-base font-bold text-base md:text-xl leading-none mb-2" ]
                        [ text "Jo Bloggerson" ]
                    , p [ class "text-gray-600 text-xs md:text-base" ]
                        [ text "Minimal Blog Tailwind CSS template by "
                        , a [ class "text-green-500 no-underline hover:underline", href "https://www.tailwindtoolbox.com" ]
                            [ text "TailwindToolbox.com" ]
                        ]
                    ]
                , div [ class "justify-end" ]
                    [ button [ class "bg-transparent border border-gray-500 hover:border-green-500 text-xs text-gray-500 hover:text-green-500 font-bold py-2 px-4 rounded-full" ]
                        [ text "Read More" ]
                    ]
                ]
            , text "\t\t"
            , hr [ class "border-b-2 border-gray-400 mb-8 mx-4" ]
                []
            , div [ class "font-sans flex justify-between content-center px-4 pb-12" ]
                [ div [ class "text-left" ]
                    [ span [ class "text-xs md:text-sm font-normal text-gray-600" ]
                        [ text "< Previous Post" ]
                    , br []
                        []
                    , p []
                        [ a [ class "break-normal text-base md:text-sm text-green-500 font-bold no-underline hover:underline", href "#" ]
                            [ text "Blog title" ]
                        ]
                    ]
                , div [ class "text-right" ]
                    [ span [ class "text-xs md:text-sm font-normal text-gray-600" ]
                        [ text "Next Post >" ]
                    , br []
                        []
                    , p []
                        [ a [ class "break-normal text-base md:text-sm text-green-500 font-bold no-underline hover:underline", href "#" ]
                            [ text "Blog title" ]
                        ]
                    ]
                ]
            , text "\t"
            ]
        , footer [ class "bg-white border-t border-gray-400 shadow" ]
            [ div [ class "container max-w-4xl mx-auto flex py-8" ]
                [ div [ class "w-full mx-auto flex flex-wrap" ]
                    [ div [ class "flex w-full md:w-1/2 " ]
                        [ div [ class "px-8" ]
                            [ h3 [ class "font-bold text-gray-900" ]
                                [ text "About" ]
                            , p [ class "py-4 text-gray-600 text-sm" ]
                                [ text "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas vel mi ut felis tempus commodo nec id erat. Suspendisse consectetur dapibus velit ut lacinia.\t\t\t\t\t\t" ]
                            ]
                        ]
                    , div [ class "flex w-full md:w-1/2" ]
                        [ div [ class "px-8" ]
                            [ h3 [ class "font-bold text-gray-900" ]
                                [ text "Social" ]
                            , ul [ class "list-reset items-center text-sm pt-3" ]
                                [ li []
                                    [ a [ class "inline-block text-gray-600 no-underline hover:text-gray-900 hover:text-underline py-1", href "#" ]
                                        [ text "Add social link" ]
                                    ]
                                , li []
                                    [ a [ class "inline-block text-gray-600 no-underline hover:text-gray-900 hover:text-underline py-1", href "#" ]
                                        [ text "Add social link" ]
                                    ]
                                , li []
                                    [ a [ class "inline-block text-gray-600 no-underline hover:text-gray-900 hover:text-underline py-1", href "#" ]
                                        [ text "Add social link" ]
                                    ]
                                ]
                            ]
                        ]
                    ]
                ]
            ]
        ]
